### ISSUE TITLE
Python logging not working as expected

### ISSUE THREAD

**Issue by sonowz** [sonowz/graduate-adventure#34]
All logs that should go to `loginview.log` is written to `crawler.log`.
It seems logging [codes](https://github.com/LastOne817/graduate-adventure/blob/master/backend/core/crawler.py) in `core/crawler.py` overrides [codes](https://github.com/LastOne817/graduate-adventure/blob/LoginAPI/backend/login/views.py) in `login/view/py`.
I think logging logic should be changed somehow.

**Comment by sonowz** [comment]
This is also causing build failure with my PR, [Appveyor page](https://ci.appveyor.com/project/LastOne817/graduate-adventure/build/1.0.83/job/xi7s5jxqi2lhonmu#L712)
[Travis build](https://travis-ci.org/LastOne817/graduate-adventure/builds/193637780) shows more exact problem.
```
python backend/manage.py migrate
Traceback (most recent call last):
  File "backend/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 342, in execute
    self.check()
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\commands\migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\projects\graduate-adventure\backend\graduate\urls.py", line 25, in <module>
    import login.urls
  File "C:\projects\graduate-adventure\backend\login\urls.py", line 2, in <module>
    from login.views import login_page, LoginRequest, test
  File "C:\projects\graduate-adventure\backend\login\views.py", line 5, in <module>
    from core.crawler import crawl_credit, crawl_major
  File "C:\projects\graduate-adventure\backend\core\crawler.py", line 7, in <module>
    os.makedirs(os.getcwd() + '/log', exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
Command exited with code 1
```

**Comment by dj-shin** [comment]
I guess I misused `logging.basicConfig`. To create multiple log files, [this](http://stackoverflow.com/questions/17035077/python-logging-to-multiple-log-files-from-different-classes) should be helpful.

If this issue is urgent, resolve this issue by yourself if you please.
